version: "3.4"

services:
  js:
    build:
      context: .
    volumes:
      - ./:/typerunner
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app

  app:
    build:
      context: .
    volumes:
      - ./:/typerunner
    env_file:
      - .env
    ports:
      - 8443:8443
    depends_on:
      - postgres
    networks:
      - app
    command: [sh, -c, "node src/index.js"]

  postgres:
    image: postgres:10-alpine
    env_file:
      - .env
    networks:
      - app

networks:
  app:
