version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    depends_on:
      - postgres
      - spa
    networks:
      - app
    command: [sh, -c, "node src/index.js"]
    ports:
      - 8443:8443

  spa:
    image: type-runner-spa:latest
    ports:
      - "80:80"
    networks:
      - app

  postgres:
    image: postgres:10-alpine
    env_file:
      - .env
    networks:
      - app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  app:
