version: "3.4"

services:
  js:
    build:
      context: .
    volumes:
      - ./:/typerunner
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app

  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - app

networks:
  app:
